### ISSUE TITLE
Unable to extract JS player URL

### ISSUE THREAD

**Issue by eijkboy** [l1ving/youtube-dl#12]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.09.20**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
SEE BELOW
```

## Description

Hi All,

```
$ youtube-dl -v -F https://youtu.be/0Pk3Uqm2qAk
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', 'https://youtu.be/0Pk3Uqm2qAk']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.09.20
[debug] Python version 3.7.3 (CPython) - Linux-4.19.0-9-cloud-amd64-x86_64-with-debian-10.4
[debug] exe versions: ffmpeg 4.3.1-static, ffprobe 4.3.1-static
[debug] Proxy map: {}
[youtube] 0Pk3Uqm2qAk: Downloading webpage
[youtube] 0Pk3Uqm2qAk: Downloading embed webpage
ERROR: Unable to extract JS player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/debian/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/home/debian/bin/youtube-dl/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/home/debian/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 2101, in _real_extract
    ASSETS_RE, embed_webpage, 'JS player URL')
  File "/home/debian/bin/youtube-dl/youtube_dl/extractor/common.py", line 1010, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract JS player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by awei78** [comment]
extractor\youtube.py, line 2089, modify ASSETS_RE = r'"assets":.+?"js":\s*("[^"]+")' to:
`ASSETS_RE = [
                            r'"assets":.+?"js":\s*("[^"]+")',
                            r'"jsUrl":("[^"]+")'
                        ]`

**Comment by l1ving** [comment]
I'll close if solved

**Comment by l1ving** [comment]
Actually, I'd appreciate a pull to fix this, or I'll do it myself

**Comment by evolution-ant** [comment]
great , it's work for me !

**Comment by kwejejwrfnfn** [comment]
One question. When I change this in YouTube.py - how can I install youtube-dl manually ? Can somebody explain that to me? I have to upload the zip to my server & then? Because YouTube-dl -U (Update) is not working since the old repo is closed.

**Comment by l1ving** [comment]
Just wget the file

**Comment by l1ving** [comment]
@awei78 This is the only instance of it I can find in that file. Did you get the line number wrong?
![Screenshot_20201029_104607](https://user-images.githubusercontent.com/17222512/97589509-f7231f00-19d3-11eb-96c3-f3988823a3e4.png)

**Comment by l1ving** [comment]
https://github.com/l1ving/youtube-dl/blob/master/youtube_dl/extractor/youtube.py#L1958

**Comment by ffabio81** [comment]
Hi l1ving,

I fixed only line #1958 and it seems to work.

**Comment by kwejejwrfnfn** [comment]
But how can I wget this new YouTube-dl. When I do this...

sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl
sudo chmod a+rx /usr/local/bin/youtube-dl

I get the old file. Where do I get the newest release from 2 hours ago with this fix?

Regards

**Comment by l1ving** [comment]
> Where do I get the newest release from 2 hours ago with this fix?


Ohh I see. Git clone this repository and run `make` and `sudo make install` inside the folder. I can add proper releases later today

**Comment by kwejejwrfnfn** [comment]
Yeah - would be cool if you can do it - because conversion is not working since 2 days I los 10.000 of user because of not working conversions.

**Comment by l1ving** [comment]
Unfortunately I can't build a release as I cannot download pandoc from the aur, all the mirrors are offline. It's late here but I can try building pandoc 
from source tomorrow

**Comment by BenarBloemendal** [comment]
Any pr

> Unfortunately I can't build a release as I cannot download pandoc from the aur, all the mirrors are offline. It's late here but I can try building pandoc from source tomorrow

Any progress of the release build ?

**Comment by l1ving** [comment]
Well currently I'm waiting for Arch to finish updating, I had to add a secondary mirror and ran Syu out of habit. Once that's done I should be able to release, fingers crossed

**Comment by l1ving** [comment]
Done @BenarBloemendal @kwejejwrfnfn

**Comment by wtfdewuno** [comment]
can someone update the AUR

**Comment by l1ving** [comment]
you'll have to ask the package maintainer on the aur, or build your own package

**Comment by dirkf** [comment]
The linked PR causes this result:
```youtube-dl -v -F 'https://www.youtube.com/watch?v=XcATvu5f9vE'
[debug] System config: ['--prefer-ffmpeg']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', 'https://www.youtube.com/watch?v=XcATvu5f9vE']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.09.20
[debug] Python version 3.5.2 (CPython) - Linux-4.4.0-193-generic-i686-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 4.3, avprobe 4.3, ffmpeg 4.3, ffprobe 4.3
[debug] Proxy map: {}
[youtube] XcATvu5f9vE: Downloading webpage
[youtube] {18} signature length 109, html5 player ec262be6
[youtube] {137} signature length 109, html5 player ec262be6
[youtube] {248} signature length 109, html5 player ec262be6
[youtube] {399} signature length 105, html5 player ec262be6
[youtube] {136} signature length 109, html5 player ec262be6
[youtube] {247} signature length 109, html5 player ec262be6
[youtube] {398} signature length 109, html5 player ec262be6
[youtube] {135} signature length 105, html5 player ec262be6
[youtube] {244} signature length 109, html5 player ec262be6
[youtube] {397} signature length 109, html5 player ec262be6
[youtube] {134} signature length 109, html5 player ec262be6
[youtube] {243} signature length 109, html5 player ec262be6
[youtube] {396} signature length 109, html5 player ec262be6
[youtube] {133} signature length 109, html5 player ec262be6
[youtube] {242} signature length 109, html5 player ec262be6
[youtube] {395} signature length 109, html5 player ec262be6
[youtube] {160} signature length 109, html5 player ec262be6
[youtube] {278} signature length 109, html5 player ec262be6
[youtube] {394} signature length 109, html5 player ec262be6
[youtube] {140} signature length 109, html5 player ec262be6
[youtube] {249} signature length 105, html5 player ec262be6
[youtube] {250} signature length 109, html5 player ec262be6
[youtube] {251} signature length 109, html5 player ec262be6
Traceback (most recent call last):
  File "/usr/bin/youtube-dl", line 9, in <module>
    load_entry_point('youtube-dl==2020.9.20', 'console_scripts', 'youtube-dl')()
  File "/usr/lib/python3/dist-packages/youtube_dl/__init__.py", line 479, in main
    _real_main(argv)
  File "/usr/lib/python3/dist-packages/youtube_dl/__init__.py", line 469, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 2019, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 2348, in _real_extract
    mobj = re.search(r'(?s)Provided to YouTube by [^\n]+\n+(?P<track>[^??]+)??(?P<artist>[^\n]+)\n+(?P<album>[^\n]+)(?:.+????\s*(?P<release_year>\d{4})(?!\d))?(?:.+?Released on\s*:\s*(?P<release_date>\d{4}-\d{2}-\d{2}))?(.+?\nArtist\s*:\s*(?P<clean_artist>[^\n]+))?', video_description)
  File "/usr/lib/python3.5/re.py", line 173, in search
    return _compile(pattern, flags).search(string)
  File "/usr/lib/python3.5/re.py", line 293, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.5/sre_compile.py", line 536, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.5/sre_parse.py", line 829, in parse
    p = _parse_sub(source, pattern, 0)
  File "/usr/lib/python3.5/sre_parse.py", line 437, in _parse_sub
    itemsappend(_parse(source, state))
  File "/usr/lib/python3.5/sre_parse.py", line 778, in _parse
    p = _parse_sub(source, state)
  File "/usr/lib/python3.5/sre_parse.py", line 437, in _parse_sub
    itemsappend(_parse(source, state))
  File "/usr/lib/python3.5/sre_parse.py", line 641, in _parse
    source.tell() - here + len(this))
sre_constants.error: multiple repeat at position 99
```

**Comment by dirkf** [comment]
And 
```
 youtube-dl -v -F 'https://youtu.be/0Pk3Uqm2qAk'
[debug] System config: ['--prefer-ffmpeg']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', 'https://youtu.be/0Pk3Uqm2qAk']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.09.20
[debug] Python version 3.5.2 (CPython) - Linux-4.4.0-193-generic-i686-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 4.3, avprobe 4.3, ffmpeg 4.3, ffprobe 4.3
[debug] Proxy map: {}
[youtube] 0Pk3Uqm2qAk: Downloading webpage
ERROR: 0Pk3Uqm2qAk: YouTube said: Unable to extract video data
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1910, in _real_extract
    'YouTube said: %s' % unavailable_message, expected=True, video_id=video_id)
youtube_dl.utils.ExtractorError: 0Pk3Uqm2qAk: YouTube said: Unable to extract video data
```
So it doesn't seem to fix the original problem.
