### ISSUE TITLE
Request for iQ.com

### ISSUE THREAD

**Issue by kartara** [l1ving/youtube-dl#27]
## Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running youtube-dl version **2020.11.01**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs violate any copyrights
- [X] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

https://www.iq.com/play/19rrhxvgyh
https://www.iq.com/play/19rxonx1ow
https://www.iq.com/play/19rxzkd0xs
https://www.iq.com/play/19rxwkrpgk
https://www.iq.com/play/19ryby9170

## Description

Hello! So, this is iQiyi's new international site. Someone told me that it's the same extractors as iQiyi.com. I hope it can be incorporated to include iq.com, along with the ability to download subtitles. :)

Verbose log:
`[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.iq.com/play/19ryby9170?lang=en_us']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.11.01.1
[debug] Python version 3.6.9 (CPython) - Linux-4.19.112+-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8
[debug] Proxy map: {}
[generic] 19ryby9170?lang=en_us: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 19ryby9170?lang=en_us: Downloading webpage
[generic] 19ryby9170?lang=en_us: Extracting information
ERROR: Unsupported URL: https://www.iq.com/play/19ryby9170?lang=en_us
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/generic.py", line 3382, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.iq.com/play/19ryby9170?lang=en_us`

**Comment by kartara** [comment]
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.iq.com/play/19ryby9170?lang=en_us']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.11.01.1
[debug] Python version 3.6.9 (CPython) - Linux-4.19.112+-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8
[debug] Proxy map: {}
[generic] 19ryby9170?lang=en_us: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 19ryby9170?lang=en_us: Downloading webpage
[generic] 19ryby9170?lang=en_us: Extracting information
ERROR: Unsupported URL: https://www.iq.com/play/19ryby9170?lang=en_us
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/generic.py", line 3382, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.iq.com/play/19ryby9170?lang=en_us
